name: FalchusPunishlist
version: ${project.version}
api-version: 1.13
description: Protect your server without staff.
main: com.falchus.punishlist.spigot.Main
author: Falchus
website: falchus.com/punishlist

depend: [FalchusLib]